services:
  - type: web
    name: gestion-bancaire
    runtime: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DATABASE_URL
        sync: false
